---
title: "Emogo V1 Analysis"
author: "Martin Zettersten"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(ggplot2)
library(viridisLite)
library(lme4)
```

## Read in data

```{r}
data_path <- here("data-analysis","data","v1","processed", "emogo-v1-alldata-anonymized.csv")
d <- read_csv(data_path)
d <- d %>%
  filter(
    !(trial_type %in% c("show-reward"))
  )
```

## Adding some useful columns

Adding columns to characterize participant choices.

```{r}
d <- d %>%
  mutate(
    trial_number = case_when(
      trial_index<8 ~ trial_index,
      trial_index<199 ~ 7+(trial_index-7)/2,
      TRUE ~ trial_index-96
    )
  ) %>%
  relocate(trial_number,.after=trial_index) %>%
  mutate(
    test_trial_number = case_when(
      trial_number<7 ~ NA_real_,
      trial_number<103 ~ trial_number-6,
      TRUE ~ NA_real_
    )
  ) %>%
  relocate(test_trial_number,.after=trial_number) %>%
  mutate(
    block_trial_number = case_when(
      test_trial_number < 49 ~ test_trial_number,
      TRUE ~ test_trial_number - 48),
    block_trial_number_c = block_trial_number - 24.5
  ) %>%
  relocate(block_trial_number,.after=test_trial_number) %>%
  relocate(block_trial_number_c,.after=block_trial_number) %>%
  mutate(
    explore_block = case_when(
      test_trial_number<9 ~ 1,
      test_trial_number<17 ~ 2,
      test_trial_number<25 ~ 3,
      test_trial_number<33 ~ 4,
      test_trial_number < 41 ~ 5,
      test_trial_number < 49 ~ 6,
      test_trial_number < 57 ~ 7,
      test_trial_number<65 ~ 8,
      test_trial_number<73 ~ 9,
      test_trial_number<81 ~ 10,
      test_trial_number <89 ~ 11,
      test_trial_number <97 ~ 12,
      TRUE ~ NA_real_
    )
  ) %>%
  mutate(
    max_reward_choice = case_when(
      reward_score_unadjusted ==8 ~ 1,
      !is.na(test_trial_number) ~ 0,
      TRUE ~ NA_real_
    )
  ) %>%
  mutate(
    cur_structure_condition=case_when(
      test_trial_number < 49 ~ structure_condition,
      !is.na(test_trial_number) & match_condition == "match" ~ structure_condition,
       test_trial_number >= 49 & structure_condition == "emotion" ~ "model",
      test_trial_number >= 49 & structure_condition == "model" ~ "emotion"
    )
  ) %>%
  mutate(block = case_when(
      test_trial_number < 49 ~ 1,
      test_trial_number >= 49 ~ 2,
      TRUE ~ NA_real_
    ))
  
```

## Check data {.tabset}

### attention check

```{r}
attention_check <- d %>%
  filter(trial_index %in% c(4,5)) %>%
  mutate(
    attention_check_correct_choice = case_when(
      trial_index == 4 ~ "stimuli/horse.jpg",
      trial_index == 5 ~ "stimuli/hammer.jpg"
    ),
    check_correct = ifelse(attention_check_correct_choice==choiceImage,1,0)
  ) %>%
  group_by(subject) %>%
  summarize(
    N=n(),
    avg_correct = mean(check_correct)
  )

passed_attention_check <- attention_check %>%
  filter(avg_correct ==1) %>%
  pull(subject)
```

### Total time

```{r}
total_time <- d %>%
  filter(trial_index==206) %>%
  select(subject,time_elapsed) %>%
  distinct() %>%
  mutate(time_mins = time_elapsed/1000/60)

#Minumum time
min(total_time$time_mins)

#Any subjects with times under 4 minutes?
subjects_too_fast <- total_time %>%
  filter(time_mins<4)

subjects_too_fast %>%
  pull(subject)
```

### Check image location selection

```{r}
percent_location_selections <- d %>%
  filter(!is.na(test_trial_number)) %>%
  group_by(subject,choiceLocation) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

#any frequencies above 80%?
subjects_same_location_exclusion <- percent_location_selections %>%
  filter(freq>0.8) 

subjects_same_location_exclusion %>%
  distinct(subject) %>%
  pull(subject)
```

### Reward ranks

```{r}
reward_rank <- d %>%
  filter(subject %in% passed_attention_check) %>%
  filter(test_trial_number==96) %>%
  select(subject,structure_condition,match_condition,score_after_trial)

median_score <- median(reward_rank$score_after_trial)

ggplot(reward_rank,aes(x=score_after_trial))+
  geom_histogram()+
  geom_vline(xintercept = median_score)

ggplot(reward_rank,aes(x=score_after_trial,color=match_condition))+
  geom_density()+
  facet_wrap(~structure_condition)

subjects_top_50 <- reward_rank %>%
  filter(score_after_trial>=median_score) %>%
  select(subject)

write_csv(subjects_top_50,here("data-analysis","data","v1","processed","subjects_top_50.csv"))

conditions_top_50 <- reward_rank %>%
  filter(subject %in% subjects_top_50$subject) %>%
  group_by(structure_condition,match_condition) %>%
  tally()
conditions_top_50
```

### Final tally

```{r}
#exclude any participants who meet exclusion criteria
d <- d %>%
  filter(subject %in% passed_attention_check) %>%
  filter(!(subject %in% subjects_same_location_exclusion)) %>%
  filter(!(subject %in% subjects_too_fast))

d %>%
  distinct(subject,structure_condition,match_condition) %>%
  group_by(structure_condition,match_condition) %>%
  tally()
```


## Summarize

```{r}
subject_by_block <- d %>%
  filter(!is.na(explore_block)) %>%
  group_by(subject,match_condition,structure_condition,explore_block) %>%
  summarize(
    max_choice_percent=mean(max_reward_choice)
  )

summarize_by_block <- subject_by_block %>%
  group_by(explore_block) %>%
  summarize(
    N=n(),
    max_choice = mean(max_choice_percent),
    se = sqrt(var(max_choice_percent, na.rm = TRUE)/N),
    ci=qt(0.975, N-1)*sd(max_choice_percent,na.rm=TRUE)/sqrt(N),
    lower_ci=max_choice-ci,
    upper_ci=max_choice+ci,
    lower_se=max_choice-se,
    upper_se=max_choice+se
  )

summarize_by_block_by_condition <- subject_by_block %>%
  group_by(match_condition,structure_condition,explore_block) %>%
  summarize(
     N=n(),
    max_choice = mean(max_choice_percent),
    se = sqrt(var(max_choice_percent, na.rm = TRUE)/N),
    ci=qt(0.975, N-1)*sd(max_choice_percent,na.rm=TRUE)/sqrt(N),
    lower_ci=max_choice-ci,
    upper_ci=max_choice+ci,
    lower_se=max_choice-se,
    upper_se=max_choice+se
  )
```

## Plots

```{r}
ggplot(subject_by_block,aes(explore_block,max_choice_percent))+
  geom_point(size=1.5,alpha=0.1,aes(group=subject))+
  geom_line(alpha=0.1,aes(group=subject))+
  geom_point(data=summarize_by_block,aes(y=max_choice),size=2,color="black")+
  geom_line(data=summarize_by_block,aes(y=max_choice),size=1.2,color="black")+
  geom_errorbar(data=summarize_by_block,aes(y=max_choice,ymin=lower_se,ymax=upper_se),width=0,color="black")+
  geom_vline(xintercept=6.5,linetype="dotted")+
  geom_hline(yintercept=0.25,linetype="dashed")+
  theme(legend.position="none")+
  scale_x_continuous(breaks=seq(1,12))+
  xlab("Block (8 Trials = 1 Block)")+
  ylab("Percent reward-maximizing choices")

ggplot(summarize_by_block_by_condition,aes(explore_block,max_choice, color=structure_condition,shape=match_condition,linetype=match_condition))+
  geom_point(size=1.5,alpha=0.5)+
  geom_line(alpha=0.5)+
  geom_point(aes(y=max_choice),size=2)+
  geom_line(aes(y=max_choice),size=1.2)+
  geom_errorbar(aes(y=max_choice,ymin=lower_se,ymax=upper_se),width=0)+
  geom_vline(xintercept=6.5,linetype="dotted")+
  geom_hline(yintercept=0.25,linetype="dashed")+
  #theme(legend.position="none")+
  scale_x_continuous(breaks=seq(1,12))+
  xlab("Block (8 Trials = 1 Block)")+
  ylab("Percent reward-maximizing choices")


ggplot(subject_by_block,aes(explore_block,max_choice_percent, group=subject))+
  #geom_point(size=1.5,alpha=0.5)+
  geom_line(alpha=0.5)+
  geom_vline(xintercept=6.5,linetype="dotted")+
  geom_hline(yintercept=0.25,linetype="dashed")+
  theme(legend.position="none")+
  facet_wrap(~structure_condition+match_condition)+
  scale_x_continuous(breaks=seq(1,12))+
  xlab("Block (8 Trials = 1 Block)")+
  ylab("Percent reward-maximizing choices")
```

## Model {.tabset}

### Main

```{r}
#recenter vars
d <- d %>%
  mutate(
    structure_condition_c = case_when(
      structure_condition == "model" ~ -0.5,
      structure_condition == "emotion" ~ 0.5),
    cur_structure_condition_c = case_when(
      cur_structure_condition == "model" ~ -0.5,
      cur_structure_condition == "emotion" ~ 0.5),
    match_condition_c = case_when(
      match_condition == "match" ~ 0.5,
      match_condition == "mismatch" ~ -0.5
    ),
    block_c = case_when(
      test_trial_number < 49 ~ -0.5,
      TRUE ~ 0.5
    )
  )

#fit model
#m <- glmer(max_reward_choice ~ cur_structure_condition_c*match_condition_c*block_c*block_trial_number_c + (1+block_c*block_trial_number_c|subject)+(1|choiceImage),data=d, family=binomial)
#m <- glmer(max_reward_choice ~ cur_structure_condition_c*match_condition_c*block_c*block_trial_number_c + (1+block_trial_number_c||subject)+(1|choiceImage),data=d, family=binomial,glmerControl(optimizer="bobyqa"))

## the above models don't converge - will go through the pruning process more rigorously

m <- glmer(max_reward_choice ~ cur_structure_condition_c*match_condition_c*block_c*block_trial_number_c+ (1|subject)+(1|choiceImage),data=d, family=binomial,glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=20000)))
summary(m)
```

### Follow-up models

trying to sort out how to look at individual conditions and blocks

```{r}
m <- glmer(max_reward_choice ~ cur_structure_condition_c*block_trial_number_c+ (1+block_trial_number_c|subject)+(1|choiceImage),data=d, family=binomial)
summary(m)

m <- glmer(max_reward_choice ~ match_condition_c*block_trial_number_c*block_c+ (1+block_trial_number_c|subject)+(1|choiceImage),data=d, family=binomial)
summary(m)

m <- glmer(max_reward_choice ~ match_condition_c*block_trial_number_c+ (1+block_trial_number_c|subject)+(1|choiceImage),data=filter(d,block==2), family=binomial)
summary(m)
m <- glmer(max_reward_choice ~ match_condition_c*block_trial_number_c+ (1+block_trial_number_c|subject)+(1|choiceImage),data=filter(d,block==1), family=binomial)
summary(m)#not really sure why there should be a match effect here... Noise?
```



